### ISSUE TITLE
setup checkin' webinars for all IOL Round 1 fellows

### ISSUE THREAD

**Issue by tvol** [creativecommons/Institute-for-Open-Leadership#21]

**Comment by tvol** [comment]
@cablegreen @pgstacey I think we're really overdue on this. How do you wish to proceed. One approach would be for each mentor to do a checkin with her/his fellows, either via email or google hangout. In the summertime would could schedule a larger hangout for everyone to give half-year updates. What do you think?

**Comment by pgstacey** [comment]
I've been having a lot of interaction via e-mail with my two mentees -
Werner Westerman and Fátima São Simão.
I've been a bit surprised at the extent of communication - its been hefty.
Both of them have moved ahead in big ways with their open work so its been
exciting to see them really put to use everything we provided them at the
IOL.

Not sure how its been for you two or Nicole, or Nic?

What I'd love to see is a webinar that brings as many of the IOL
participants together as possible for a group update on whats happened
since the Institute but I know there are time zone challenges. Perhaps we
can get them going on blog posts?

Paul

On Tue, May 12, 2015 at 3:41 PM, Timothy Vollmer notifications@github.com
wrote:

> @cablegreen https://github.com/cablegreen @pgstacey
> https://github.com/pgstacey I think we're really overdue on this. How
> do you wish to proceed. One approach would be for each mentor to do a
> checkin with her/his fellows, either via email or google hangout. In the
> summertime would could schedule a larger hangout for everyone to give
> half-year updates. What do you think?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/Institute-for-Open-Leadership/issues/21#issuecomment-101446198
> .

## 

Paul Stacey
Associate Director of Global Learning
Creative Commons
pstacey@creativecommons.org

State of the Commons Report https://stateof.creativecommons.org/report/
Get Creative Commons Updates http://bit.ly/commonsnews

**Comment by cablegreen** [comment]
Great ideas all.

I'll take point re: 
(1) sending a note to all mentors - asking them to check in with their fellows.  I'll ask mentors to encourage their fellows to think about a blog post.
(2) Schedule a hangout for all fellows to give their 1/2 year updates.  
(3) I'll ping Puneet to see if he still wants to work with his fellows. If not - we'll need to assign remaining mentors to Puneet's fellows.

**Comment by tvol** [comment]
@cablegreen ok thanks. I'm in touch with my fellows, but not as much as @pgstacey . I'm gonna ping them again to see what's going on.
